### ISSUE TITLE
Liberty 스킨이 적용된 채로 Reload시 발생하는 오류

### ISSUE THREAD

**Issue by 1ongames** [namu-theseed/theseed-skin-liberty#138]
the seed 자체의 오류인지 아니면 스킨의 오류인지는 모르겠으나, 해당 오류가 빌생하며 작동하지 않습니다.

app initialization failed

ReferenceError: ViewName_delete is not defined
ReferenceError: ViewName_delete is not defined
    at _0x2f2d7e (https://www.alphawiki.org/skins/liberty/eiitehfd.cdba4f3553d4685e4e51.js:1:204748)
    at B.NuJBbRrAE (https://www.alphawiki.org/skins/liberty/eiitehfd.cdba4f3553d4685e4e51.js:1:210377)
    at https://www.alphawiki.org/skins/liberty/eowednyd.cf1ca5174076fba18bc9.js:2:301340
    at https://www.alphawiki.org/skins/liberty/eowednyd.cf1ca5174076fba18bc9.js:2:308951
    at Array.forEach (<anonymous>)
    at https://www.alphawiki.org/skins/liberty/eowednyd.cf1ca5174076fba18bc9.js:2:308930
    at B._withCommit (https://www.alphawiki.org/skins/liberty/eowednyd.cf1ca5174076fba18bc9.js:2:310747)
    at B.commit (https://www.alphawiki.org/skins/liberty/eowednyd.cf1ca5174076fba18bc9.js:2:308904)
    at B.commit (https://www.alphawiki.org/skins/liberty/eowednyd.cf1ca5174076fba18bc9.js:2:308374)
    at updateAsyncData (https://www.alphawiki.org/skins/liberty/eiitehfd.cdba4f3553d4685e4e51.js:1:341713)

p.s: 알파위키 기준 상단에 표시되는 header가 이상하게 표시되는 오류가 있음. 엔진 오류로 추정
![Screenshot_20241103_165758_Chrome](https://github.com/user-attachments/assets/ba54f2fb-3b95-4c89-b343-88c1f2868af1)

**Comment by 1ongames** [comment]
해당 오류 해결된 것으로 보이네요
